### ISSUE TITLE
Add wiki

### ISSUE THREAD

**Issue by Zumbalamambo** [mfdeakin/Crowds#1]
May I know how do I run the code?

**Comment by mfdeakin** [comment]
Could you clarify? If you just want to run the simple simulation (consisting of 3 circular pedestrians navigating around each other and a single short wall to their own destinations through a naive implementation of gradient descent of their energy functions) I've set up; run 'python3 crowds.py'. This produces a set of images for each timestep as the pedestrians move through the scene.
You can use the mkvideos script to stitch these images together into videos.
Note this requires python 3, numpy, and PIL.

**Comment by Zumbalamambo** [comment]
Please add some wiki
